_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "ProposalNetworkWithMasks"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  FPN:
    NORM: "GN"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: RepPointsGenerator
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    NUM_POINTS: 9
    HEAD_NAME: RepPointsInitHead
    SAMPLE_MODE: "inside"
  RPN:
    POST_NMS_TOPK_TEST: 2000
OUTPUT_DIR: ./train_log/rep_points_rpn_R_50_FPN_GN_1x_inside_box
