_BASE_: "base.yaml"
MODEL:
  META_ARCH:
    NAME: AnchorHead
    IOU_THRESHOLDS: [0.3, 0.7]
    IOU_LABELS: [0, -1, 1]
    FEAT_ADAPTION: unsupervised
    LOSS_LOC_REFINE_WEIGHT: 5.0
  ANCHOR_GENERATOR:
    SIZES: !!python/object/apply:eval ["[[x, x * 2**(1.0/3), x * 2**(2.0/3) ] for x in [32, 64, 128, 256, 512 ]]"]


