from detectron2.modeling.meta_arch import build_model

from .pnwm import ProposalNetworkWithMasks
from .pvrcnn import ProposalVisibleRCNN
from .fcos import FCOS
from .fcosv2 import FCOSV2
from .retinanetwa import RetinaNetWithAnchor
from .fcoswa import FCOSWithAnchor
from .pvrcnnwa import ProposalVisibleRCNNWithAnchor
from .fcos_anchor import FCOSAnchor
from .rpd import RepPointsDetector
from .retinadc import DeformableConvRetinaNet
from .retina_reppoints import ReppointsRetinaNet
from .retina_points import PointRetinaNet
from .retina_fcosv2 import FCOSRetinaNet
from .retina_fcosv2_nc import FCOSNCRetinaNet
from .retina_centerness_assign import CenternessRetinaNet
from .fcosv3 import FCOSV3
from .rpd_centerness import RepPointsCenterness
from .rpd_nearest_centerness import RepPointsNearestCenterness
#from .fcos_reppoints import FCOSRepPoints
from .fcos_rpd_iou import FCOSRepPoints