from detectron2.modeling.meta_arch import build_model

from .pnwm import ProposalNetworkWithMasks
from .pvrcnn import ProposalVisibleRCNN
from .fcos import FCOS
from .fcosv2 import FCOSV2
from .retinanetwa import RetinaNetWithAnchor
from .fcoswa import FCOSWithAnchor
from .pvrcnnwa import ProposalVisibleRCNNWithAnchor
from .fcos_anchor import FCOSAnchor
from .rpd import RepPointsDetector
from .retinadc import DeformableConvRetinaNet
from .retina_reppoints import ReppointsRetinaNet
from .retina_points import PointRetinaNet
from .retina_fcosv2 import FCOSRetinaNet
from .retina_fcosv2_nc import FCOSNCRetinaNet
from .retina_centerness_assign import CenternessRetinaNet
from .fcosv3 import FCOSV3
from .rpd_centerness import RepPointsCenterness
from .corner_net import CornerNet

#from .fcos_rpd import FCOSRepPoints
from .fcos_dcn import FCOSRepPoints
#from .fcos_rpd_exp import FCOSRepPoints
#from .fcos_rpd_topk_per_box import FCOSRepPoints
#from .fcos_rpd_less_center import FCOSRepPoints
#from .fcos_rpd_dcnv2 import FCOSRepPoints
#from .fcos_rpd_conv_points import FCOSRepPoints
#from .fcos_rpd_mask_assign import FCOSRepPoints
#from .fcos_rpd_normalized_centerness import FCOSRepPoints