_BASE_: "base.yaml"
MODEL:
  WEIGHTS: "catalog://ImageNetPretrained/FAIR/X-152-32x8d-IN5k"
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 152
    DEFORM_ON_PER_STAGE: [False, True, True, True]

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  STEPS: (120000, 160000)
  MAX_ITER: 180000