_BASE_: "Base-Fcos.yaml"
MODEL:
  META_ARCHITECTURE: "FCOSTopK"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
DATASETS:
  TEST: ("coco_objects365_val_with_masks",)
OUTPUT_DIR: ./train_log/0830_FCOS_top5_R_50_FPN_1x
#OUTPUT_DIR: ./train_log/0830_FCOS_top1_R_50_FPN_1x