_BASE_: "Base-Fcos.yaml"
MODEL:
  META_ARCHITECTURE: "FCOSV3"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  MASK_ON: True
SOLVER:
  IMS_PER_BATCH: 1
OUTPUT_DIR: ./train_log/0715_gaussian5_maskthresh2_fcosv3_R_50_FPN_1x