_BASE_: "Base-RetinaNet.yaml"
MODEL:
  META_ARCHITECTURE: "PointRetinaNet"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NUM_POINTS: 2
    SAMPLE_MODE: "points"
DATASETS:
  TEST: ("coco_objects365_val_with_masks",)

VIS_PERIOD: 1024
#OUTPUT_DIR: ./train_log/0826_9points_retinanet_points_R_50_FPN_1x
OUTPUT_DIR: ./train_log/0826_2points_retinanet_points_R_50_FPN_1x
#OUTPUT_DIR: ./train_log/0706_9points_retinanet_points_R_50_FPN_1x
#OUTPUT_DIR: ./train_log/0706_2points_retinanet_points_R_50_FPN_1x
