_BASE_: "Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  META_ARCHITECTURE: "CenternessRetinaNet"
VIS_PERIOD: 1024
OUTPUT_DIR: ./train_log/0705_centerness_assign_retinanet_R_50_FPN_1x
