_BASE_: "Base-RetinaNet.yaml"
MODEL:
  META_ARCHITECTURE: "NearestRetinaNet"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
DATASETS:
  TEST: ("coco_objects365_val_with_masks",)

VIS_PERIOD: 1024
OUTPUT_DIR: ./train_log/0629_nearest_retinanet_R_50_FPN_1x
