_BASE_: "Base-RetinaNet.yaml"
MODEL:
  META_ARCHITECTURE: "DeformableConvRetinaNet"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50

VIS_PERIOD: 1024
OUTPUT_DIR: ./train_log/0629_base2_stride124816_retinanet_dc_R_50_FPN_1x
