_BASE_: "Base-RetinaNet.yaml"
MODEL:
  META_ARCHITECTURE: "ReppointsRetinaNet"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NUM_POINTS: 9
    SAMPLE_MODE: "points"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    NORM: "GN"
SOLVER:
  WARMUP_FACTOR: 0.33
  IMS_PER_BATCH: 16
DATASETS:
  TEST: ("coco_objects365_val_with_masks",)
  
VIS_PERIOD: 1024
OUTPUT_DIR: ./train_log/0703_retina_reppoints_R_50_FPN_1x