MODEL:
  META_ARCHITECTURE: "FCOSV2"
  BACKBONE:
    NAME: "build_retinanet_resnet_fpn_backbone_use_p5"
  RESNETS:
    OUT_FEATURES: ["res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]

DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)

SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (60000, 80000)
  MAX_ITER: 90000

INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)

TEST:
  EVAL_PERIOD: 0
VERSION: 2
