_BASE_: "base.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
  META_ARCH:
    NAME: AnchorHead
    IOU_THRESHOLDS: [0.4, 0.5]
    IOU_LABELS: [0, -1, 1]
    FEAT_ADAPTION: unsupervised
    LOSS_LOC_REFINE_WEIGHT: 1.0
  ANCHOR_GENERATOR:
    SIZES: !!python/object/apply:eval ["[[x, x * 2**(1.0/3), x * 2**(2.0/3) ] for x in [32, 64, 128, 256, 512 ]]"]
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
